#!/bin/bash
export TERM=xterm-256color

homes=("/root" "/home/virtu" "/home/ansible")
search_string="WELOTEC - DO NOT TRUST"
for home in "${homes[@]}"; do
    file="$home/.ssh/authorized_keys"
    if [ -f "$file" ]; then
        if grep -q "$search_string" "$file"; then
            display_help=true
            echo "$(tput setaf 1)WARNING: $file contains generic keys which are not secret $(tput sgr0)"
        fi
    fi
done

if [ "$display_help" = true ]; then
    echo "$(tput setaf 6)"
    echo "Some of the default SSH keys were found, these are not to be trusted!"
    echo "For more information on what this means and how to solve the issue"
    echo "please refer to the instructions at: https://github.com/welotec/seapath-build_debian_iso#security$(tput sgr0)"
fi
