#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

fcopy -m root,root,0755 /usr/local/sbin/hw_setup.sh
fcopy -M /etc/systemd/system/hw_setup.service

fcopy -M /etc/tuned/welo-sp-rt/tuned.conf

fcopy -M /etc/systemd/system/generate_issue.service
fcopy -m root,root,0755 /etc/update-motd.d/20-warning
$ROOTCMD mv /etc/issue /etc/issue.bak
$ROOTCMD ln -s /etc/systemd/system/generate_issue.service /etc/systemd/system/multi-user.target.wants/generate_issue.service

ainsl /etc/modules "msr"
